FROM golang:1.14

RUN mkdir /app
WORKDIR /app

ENV GO111MODULE=on

# hot reloader
# https://medium.com/easyread/today-i-learned-golang-live-reload-for-development-using-docker-compose-air-ecc688ee076
RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \
    && chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air

EXPOSE 8080

CMD air