version: '3'
services:
    app:
      build:
        context: .
        dockerfile: ./Dockerfile.dev
      volumes:
        - ./:/app
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      tty: true
      stdin_open: true
      environment:
        DATABASE_USERNAME: root
        DATABASE_PASSWORD: root
        DATABASE_HOST: mysql
        DATABASE_NAME: todo_dev
        TEST_DATABASE_NAME: todo_test
        DATABASE_PORT: 3306
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: todo_dev
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "33033:3306"
      volumes:
        - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
    driver: local